# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build before merge

on:
  pull_request:
    branches: [ master ]
    types: [opened, edited, synchronize, ready_for_review, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'sapmachine'
    - name: Build with Maven
      run: mvn verify --update-snapshots
